name: 'next version'
description: 'calculate next version number'
author: 'hugcabbage'

inputs:
  prefix:
    description: 'prefix of version number'
    required: false
    default: 'v'
  mode:
    description: 'version mode'
    required: false
    default: 1
    type: number
  repo_path:
    description: 'repository path'
    required: false
    default: '.'

outputs:
  version:
    description: 'next version number'

runs:
  using: node20
  main: dist/index.js
