name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

  test-base:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action first
        id: test-action-1
        uses: ./
        with:
          prefix: 'w'
          mode: 3

      - name: Test Local Action second
        id: test-action-2
        uses: ./

      - name: Print Output first
        run: echo "${{ steps.test-action-1.outputs.version }}"

      - name: Print Output second
        run: echo "${{ steps.test-action-2.outputs.version }}"

  test-path:
    name: GitHub Actions Test with Path
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          path: 'test-path'

      - name: Test Local Action
        id: test-action
        uses: hugcabbage/next-version@main
        with:
          mode: 3
          repo_path: 'test-path'

      - name: Print Output
        run: echo "${{ steps.test-action.outputs.version }}"
